export const GET_MOVIE_LIST = 'GET_MOVIE_LIST'
export const GET_MOVIE_LIST_SUCCESS = 'GET_MOVIE_LIST_SUCCESS'
export const GET_MOVIE_LIST_FAIL = 'GET_MOVIE_LIST_FAIL'

export const GET_TOP_RATED_MOVIE_LIST = 'GET_TOP_RATED_MOVIE_LIST'
export const GET_TOP_RATED_MOVIE_LIST_SUCCESS = 'GET_TOP_RATED_MOVIE_LIST_SUCCESS'
export const GET_TOP_RATED_MOVIE_LIST_FAIL = 'GET_TOP_RATED_MOVIE_LIST_FAIL'

